apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
      metadata:
        labels:
          app: web-app

      spec:
        containers: 
        - name: web-app-container
# This is where your Docker image will be store
# You must create a Docker Hub account and replace this with your repo.
          image: kanishk099/k8s-simple-web-app:${{ github.sha }}
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"

