name: CI/CD Pipeline to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./web-app
          file: ./web-app/Dockerfile
          push: true
          tags: kanishkagarwal2000/k8s-simple-web-app:latest

      - name: Set up Kubeconfig
        run: |
          # This assumes you have your Kubeconfig as a GitHub Secret
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./k8s/
